services:
  wikijs:
    image: ghcr.io/requarks/wiki:2
    container_name: wikijs
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./config/wikijs.env
    volumes:
      - /srv/appdata/wikijs-data:/wiki/data
      - ../../secrets/wikijs-git/id_ed25519:/wiki/data/keys/id_ed25519:ro
    networks:
      - wikinet
      - acadia_internal

  db:
    image: postgres:15-alpine
    container_name: wikijs-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /srv/appdata/wikijs-db:/var/lib/postgresql/data
    networks:
      - wikinet

networks:
  wikinet:
    driver: bridge
  acadia_internal:
    external: true
    name: infrastructure_acadia_internal
